# Generated by Django 5.1.1 on 2024-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/no-photo-user.jpg', upload_to='profile_avatar'),
        ),
    ]
